name = "plakker"
main = "src/index.js"
compatibility_date = "2025-01-15"

# Custom Domain 설정(임시로 비활성화)
# routes = [
#  { pattern = "plakker.bloupla.net", custom_domain = true, zone_name = "bloupla.net" }
# ]

[[kv_namespaces]]
binding = "PLAKKER_KV"
id = "5e59a6f63f12430aaea1b884e68bf8cd"

[[r2_buckets]]
binding = "PLAKKER_R2"
bucket_name = "plakker-storage"

[vars]
ENVIRONMENT = "production"
GEMINI_API_KEY = "AIzaSyAgLwJmesiDug0FOab3TRN8Dyv8AeTd8cA"